const { CATEGORY_OPTIONS, PRODUCT_STATUS, MERCHANT_STATUS } = require('./constants');

function createSeedState() {
  return {
    meta: {
      timeSeed: Date.UTC(2026, 3, 16, 8, 0, 0),
      timeStepMs: 60 * 1000,
      tick: 0,
      nextIds: {
        user: 3,
        merchant: 5,
        product: 9,
        order: 1,
        review: 1,
        refund: 1,
        address: 3,
        coupon: 3,
      },
    },
    settings: {
      useCloud: false,
    },
    session: {
      currentUserId: 'user_buyer_demo',
    },
    banners: [
      {
        id: 'banner_breakfast',
        title: '早餐 15 分钟起送',
        subtitle: '热豆浆、面点、轻食券限时抢',
        theme: '#2563eb',
      },
      {
        id: 'banner_medicine',
        title: '夜间药房不打烊',
        subtitle: '常备药、退热贴、儿童护理即刻送',
        theme: '#0f766e',
      },
      {
        id: 'banner_fresh',
        title: '今日生鲜满 39 减 8',
        subtitle: '水果蔬菜当日直采，支持次晨补送',
        theme: '#15803d',
      },
    ],
    categories: CATEGORY_OPTIONS,
    users: [
      {
        id: 'user_buyer_demo',
        phone: '18800001111',
        nickname: '演示买家',
        role: 'buyer',
        avatarUrl: '',
        balance: 120,
        merchantId: '',
      },
      {
        id: 'user_merchant_demo',
        phone: '16600002222',
        nickname: '掌柜小张',
        role: 'merchant',
        avatarUrl: '',
        balance: 68,
        merchantId: 'merchant_noodle_house',
      },
    ],
    merchants: [
      {
        id: 'merchant_noodle_house',
        ownerUserId: 'user_merchant_demo',
        name: '邻里面馆',
        category: 'restaurant',
        score: 4.8,
        monthlySales: 2167,
        deliveryFee: 4,
        minOrderAmount: 20,
        avgDeliveryTime: '28 分钟',
        distance: '1.4 km',
        notice: '新客立减 6 元，支持备注口味和餐具。',
        tags: ['准时达', '热销'],
        status: MERCHANT_STATUS.APPROVED,
        licenseImages: ['demo-license-1'],
        intro: '手擀面、浇头饭、晚餐套餐。',
      },
      {
        id: 'merchant_night_market',
        ownerUserId: '',
        name: '夜猫超市',
        category: 'market',
        score: 4.6,
        monthlySales: 1380,
        deliveryFee: 3,
        minOrderAmount: 25,
        avgDeliveryTime: '32 分钟',
        distance: '2.1 km',
        notice: '支持整单开发票，零食酒水 24 小时配送。',
        tags: ['夜宵补给', '满减'],
        status: MERCHANT_STATUS.APPROVED,
        licenseImages: ['demo-license-2'],
        intro: '便利店、日用百货、零食饮料。',
      },
      {
        id: 'merchant_safe_medicine',
        ownerUserId: '',
        name: '安心药房',
        category: 'medicine',
        score: 4.9,
        monthlySales: 970,
        deliveryFee: 5,
        minOrderAmount: 18,
        avgDeliveryTime: '24 分钟',
        distance: '1.1 km',
        notice: '药师在线，夜间订单优先处理。',
        tags: ['药师在线', '夜间药房'],
        status: MERCHANT_STATUS.APPROVED,
        licenseImages: ['demo-license-3'],
        intro: '常备药、外用护理、健康器械。',
      },
      {
        id: 'merchant_fresh_morning',
        ownerUserId: '',
        name: '晨鲜果蔬',
        category: 'fresh',
        score: 4.7,
        monthlySales: 1620,
        deliveryFee: 2,
        minOrderAmount: 15,
        avgDeliveryTime: '22 分钟',
        distance: '0.9 km',
        notice: '水果蔬菜每日两次补货，下雨天正常配送。',
        tags: ['次晨补送', '产地直采'],
        status: MERCHANT_STATUS.APPROVED,
        licenseImages: ['demo-license-4'],
        intro: '新鲜水果、净菜、轻食沙拉。',
      },
    ],
    products: [
      {
        id: 'product_beef_noodle',
        merchantId: 'merchant_noodle_house',
        category: 'restaurant',
        name: '招牌牛肉面',
        description: '红烧牛腩 + 手擀面，支持加辣与加蛋。',
        price: 26,
        originPrice: 29,
        stock: 60,
        sales: 480,
        rating: 4.9,
        unit: '份',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_fried_rice',
        merchantId: 'merchant_noodle_house',
        category: 'restaurant',
        name: '香菇鸡丁炒饭',
        description: '含鸡丁、青豆、玉米粒，适合单人餐。',
        price: 22,
        originPrice: 24,
        stock: 80,
        sales: 352,
        rating: 4.7,
        unit: '份',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_cola_pack',
        merchantId: 'merchant_night_market',
        category: 'market',
        name: '可乐家庭装',
        description: '2L x 2 瓶，聚会宵夜补给。',
        price: 18,
        originPrice: 20,
        stock: 45,
        sales: 214,
        rating: 4.6,
        unit: '组',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_potato_chips',
        merchantId: 'merchant_night_market',
        category: 'market',
        name: '薯片分享装',
        description: '番茄味 / 黄瓜味随机发货。',
        price: 12,
        originPrice: 14,
        stock: 70,
        sales: 289,
        rating: 4.5,
        unit: '袋',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_cold_medicine',
        merchantId: 'merchant_safe_medicine',
        category: 'medicine',
        name: '感冒灵颗粒',
        description: '家庭常备，夜间急送。',
        price: 32,
        originPrice: 36,
        stock: 50,
        sales: 176,
        rating: 4.9,
        unit: '盒',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_bandage',
        merchantId: 'merchant_safe_medicine',
        category: 'medicine',
        name: '创口贴套装',
        description: '防水透气，居家备用。',
        price: 15,
        originPrice: 18,
        stock: 90,
        sales: 122,
        rating: 4.8,
        unit: '盒',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_apple_box',
        merchantId: 'merchant_fresh_morning',
        category: 'fresh',
        name: '红富士苹果箱',
        description: '脆甜多汁，约 2.5 kg。',
        price: 39,
        originPrice: 45,
        stock: 36,
        sales: 190,
        rating: 4.8,
        unit: '箱',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
      {
        id: 'product_salad_pack',
        merchantId: 'merchant_fresh_morning',
        category: 'fresh',
        name: '轻食沙拉包',
        description: '即开即食，含油醋汁。',
        price: 16,
        originPrice: 19,
        stock: 52,
        sales: 144,
        rating: 4.6,
        unit: '份',
        status: PRODUCT_STATUS.ON_SALE,
        imageUrl: '',
      },
    ],
    addresses: [
      {
        id: 'address_home',
        userId: 'user_buyer_demo',
        contactName: '张三',
        phone: '18800001111',
        detail: '朝阳路 88 号 2 栋 602',
        tag: '家',
        isDefault: true,
      },
      {
        id: 'address_office',
        userId: 'user_buyer_demo',
        contactName: '张三',
        phone: '18800001111',
        detail: '科创园 A3 研发中心 9 层',
        tag: '公司',
        isDefault: false,
      },
    ],
    coupons: [
      {
        id: 'coupon_new_user',
        userId: 'user_buyer_demo',
        title: '新人立减券',
        amount: 6,
        minSpend: 25,
        status: 'unused',
        expiry: '2026-12-31',
      },
      {
        id: 'coupon_night',
        userId: 'user_buyer_demo',
        title: '夜宵补给券',
        amount: 8,
        minSpend: 39,
        status: 'unused',
        expiry: '2026-11-30',
      },
    ],
    cart: {
      merchantId: '',
      remark: '',
      items: [],
    },
    orders: [],
    reviews: [],
    refunds: [],
  };
}

module.exports = {
  createSeedState,
};
